name: "Academic Paper Review"

permissions:
  pull-requests: write
  contents: read

on:
  pull_request:
    paths:
      - '*.tex'
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  academic-review:
    runs-on: ubuntu-latest
    steps:
      - name: Academic Paper Review Bot
        uses: smkwlab/ai-academic-paper-reviewer@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LANGUAGE: "Japanese"
          USE_SINGLE_COMMENT_REVIEW: "false"
          EXCLUDE_PATHS: "*.bib,*.sty,*.cls,*.bbl,*.aux"
          MODEL_CODE: "models/gemini-2.0-flash"
          REVIEW_MODE: "ACADEMIC"
