name: Build and Release PDF

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/smkwlab/texlive-ja-textlint:2023c-alpine
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          # pull_request_target の場合は head.sha、tag の場合は GITHUB_REF を使用
          ref: ${{ github.event.pull_request.head.sha || github.ref }}

      - name: Check tex file existence
        id: check_src
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ inputs.file }}.tex
      - name: Build PDF file by latexmk
        if: steps.check_src.outputs.files_exists == 'true'
        run: latexmk ${{ inputs.file }}.tex
      - name: Check PDF file existence
        id: check_pdf
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ inputs.file }}.pdf
      - name: Create a release
        if: steps.check_pdf.outputs.files_exists == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ inputs.file }}.pdf
          # pull_request_target の場合は head_ref-release、tag の場合は ref_name-release
          tag_name: ${{ format('{0}-release', github.head_ref || github.ref_name) }}
          draft: false
          # タグプッシュの場合は false（正式リリース）、PRの場合は true（プレリリース）
          prerelease: ${{ github.event_name == 'pull_request_target' }}
          generate_release_notes: true
