name: Build and Release PDF

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/smkwlab/alpine-texlive-ja-textlint:latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check tex file existence
        id: check_src
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ inputs.file }}.tex
      - name: Build PDF file by latexmk
        if: steps.check_src.outputs.files_exists == 'true'
        run: latexmk ${{ inputs.file }}.tex
      - name: Check PDF file existence
        id: check_pdf
        uses: andstor/file-existence-action@v3
        with:
          files: ${{ inputs.file }}.pdf
      - name: Create a release
        if: steps.check_pdf.outputs.files_exists == 'true'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ inputs.file }}.pdf
          tag_name: ${{ github.head_ref }}-release
          draft: false
          prerelease: true
          generate_release_notes: true
