name: Build and Release PDF

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
# 以下の `document` を tex ファイルのファイル名から '.tex' を除いたものに変更
  document:
    runs-on: ubuntu-latest
    container: ghcr.io/smkwlab/texlive-ja-textlint:2023c-alpine
    steps:
      - uses: smkwlab/latex-release-action@v1
        with:
          file: ${{ github.job }}
